spring:
  application:
    name: ms-report
  profiles:
    active: ${PROFILE:default}
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://configuser:a501082a-0573-4ff0-9522-d5c3d4b2e859@localhost:7777}

server:
  port: 7070
  shutdown: ${SPRING_SERVER_SHUTDOWN:graceful}
  servlet:
    context-path: /ms-report

report:
  template: "templates/patient_report_template.md"

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}:${server.port}"
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    registerWithEureka: ${SPRING_EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
    fetchRegistry: ${SPRING_EUREKA_CLIENT_FETCH_REGISTRY:true}

# Configuración de Feign con tiempos de espera más largos
feign:
  client:
    config:
      default:
        connectTimeout: 10000     # 10 segundos para conexión
        readTimeout: 10000        # 10 segundos para lectura
      patient-service:
        connectTimeout: 10000     # 10 segundos para conexión a patient-service
        readTimeout: 10000        # 10 segundos para lectura de patient-service
        loggerLevel: full         # Añadido para depuración

  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      patientServiceBreaker:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 1000
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

ribbon:
  ServerListRefreshInterval: 3000
  ConnectTimeout: 10000          # 10 segundos para conexión
  ReadTimeout: 10000             # 10 segundos para lectura
  MaxAutoRetries: 1              # Permite un reintento
  MaxAutoRetriesNextServer: 1    # Intenta otro servidor si falla
  OkToRetryOnAllOperations: true # Permite reintento en todas las operaciones

# Configuración específica de Ribbon para patient-service
patient-service:
  ribbon:
    listOfServers: http://192.168.100.16:8082
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    PreferSameZoneEureka: true

# Ajuste de logs para depuración
logging:
  level:
    com.ms_cels.report_ms.repositories: DEBUG      # Activar logs para tus repositorios
    org.springframework.cloud.openfeign: DEBUG     # Logs de Feign
    com.netflix.discovery: INFO                    # Logs de Eureka